steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Google cloud docker auth"
    entrypoint: sh
    args:
      - "-c"
      - |
        gcloud auth configure-docker europe-west2-docker.pkg.dev

  - name: docker
    id: "Docker build and push"
    entrypoint: sh
    args:
      - "-c"
      - |
        docker build -t "europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:latest" -t "europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:${TAG_NAME}" .
        docker push "europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:latest"
        docker push "europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:${TAG_NAME}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Run container"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "cir-converter-service",
        "--image",
        "europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:latest",
        "--port",
        "5010",
        "--region",
        "europe-west2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--ingress",
        "internal-and-cloud-load-balancing",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Artifact Registry
images:
  - europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:${TAG_NAME}
  - europe-west2-docker.pkg.dev/ons-cir-mig-images/docker-images/${PROJECT_ID}:latest
